/*
 * This source file was generated by the Gradle 'init' task
 */
package workspace;

import org.junit.jupiter.api.Test;

import workspace.wiseSayingProject.Controller.WiseSayingController;

class AppTest {
    @Test void appHasAGreeting() throws Exception {
        App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        //new WiseSayingController().run();
    }
}
