/*
 * This source file was generated by the Gradle 'init' task
 */
package workspace;

import workspace.wiseSaying.WiseSayingMain;

public class App {


    public static void main(String[] args) throws Exception  {
        //System.out.println(new App().getGreeting());
        new WiseSayingMain().Main();
    }
}