/*
 * This source file was generated by the Gradle 'init' task
 */
package workspace;

import workspace.wisesaying.WiseSayingMain;

public class App {


    public static void main(String[] args) throws Exception  {
        //System.out.println(new App().getGreeting());
        new WiseSayingMain().Main();
    }
}

//한번 실행해주시겠어요?
// 넵 어떤 부분이 안되나요?
// 이런식으로 한글로 콘솔에 입력하면 한글이 깨져서 들어가는 상태로 돌아간 것 같습니다.  잠시만요 제가박살내놨나봐요
//환경 설정이 제일 어려운거 같네요.. 