/*
 *
 * This source file was generated by the Gradle 'init' task
 *  App 구동 (Controller 실행) 
 * 
 */

package workspace;

import workspace.wiseSayingProject.Controller.WiseSayingController;

public class App {


    public static void main(String[] args) throws Exception  {
        //System.out.println(new App().getGreeting());
        new WiseSayingController().run();
    }
}